# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 06:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('intName', models.CharField(blank=True, max_length=1000)),
                ('shortName', models.CharField(blank=True, max_length=3)),
                ('popular', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DemandTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('pubDate', models.DateTimeField(blank=True)),
                ('modifyDate', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=12, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('place', models.CharField(max_length=1000)),
                ('latitude', models.CharField(blank=True, max_length=1000, null=True)),
                ('longitude', models.CharField(blank=True, max_length=1000, null=True)),
                ('country', models.CharField(blank=True, max_length=1000, null=True)),
                ('countryShort', models.CharField(blank=True, max_length=3)),
                ('region', models.CharField(blank=True, max_length=1000, null=True)),
                ('city', models.CharField(blank=True, max_length=1000, null=True)),
                ('state', models.CharField(choices=[('active', 'Active'), ('nonactive', 'Non active')], default='active', max_length=10)),
                ('category', models.CharField(choices=[('rent', 'Rent'), ('service', 'Service'), ('goods', 'Goods'), ('other', 'Other')], default='service', max_length=10)),
                ('img', models.ImageField(blank=True, null=True, upload_to='media')),
                ('coast', models.CharField(blank=True, max_length=10, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('countryTable', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='travelondesk.Country')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ServiceTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('pubDate', models.DateTimeField(blank=True)),
                ('modifyDate', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=12, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('place', models.CharField(max_length=1000)),
                ('latitude', models.CharField(blank=True, max_length=1000, null=True)),
                ('longitude', models.CharField(blank=True, max_length=1000, null=True)),
                ('country', models.CharField(blank=True, max_length=1000, null=True)),
                ('countryShort', models.CharField(blank=True, max_length=3)),
                ('region', models.CharField(blank=True, max_length=1000, null=True)),
                ('city', models.CharField(blank=True, max_length=1000, null=True)),
                ('state', models.CharField(choices=[('active', 'Active'), ('nonactive', 'Non active')], default='active', max_length=10)),
                ('category', models.CharField(choices=[('rent', 'Rent'), ('service', 'Service'), ('goods', 'Goods'), ('other', 'Other')], default='service', max_length=10)),
                ('img', models.ImageField(blank=True, null=True, upload_to='media')),
                ('coast', models.CharField(blank=True, max_length=10, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('countryTable', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='travelondesk.Country')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
